version: 0.2

phases:
  build:
    commands:
      - echo Creating change set
      - aws cloudformation validate-template --template-body file://Infrastructure/ghost_blog.yml --capabilities CAPABILITY_IAM
      - aws cloudformation create-change-set --stack-name ghost-blog --change-set-name ghost-blog --template-body file://Infrastructure/ghost_blog.yml --capabilities CAPABILITY_IAM
      - echo Finished creating change set
