Type: AWS::CloudFront::Distribution
Properties: 
  DistributionConfig: 
    DefaultCacheBehavior:
      TargetOriginId: !ImportValue ELBDomainName
      ViewerProtocolPolicy: allow-all

      ForwardedValues:
        QueryString: true
        Cookies:
          Forward: all

Outputs:
  DistributionDomainName:
    Value: !GetAtt Distribution.DomainName
    Export:
      Name: DistributionDomainName