AWSTemplateFormatVersion: '2010-09-09'

Resources:
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties: 
      DistributionConfig: 
        DefaultCacheBehavior:
          TargetOriginId: !ImportValue ELBDomainName
          ViewerProtocolPolicy: allow-all

Outputs:
  DistributionDomainName:
    Value: !GetAtt Distribution.DomainName
    Export:
      Name: DistributionDomainName