AWSTemplateFormatVersion: 2010-09-09

Resources:
  CodeStarConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties: 
      ConnectionName: GhostGithubConnection
      ProviderType: GitHub

Outputs:
  ConnectionArn:
    Value: !Ref CodeStarConnection
    Export:
      Name: GhostGithubConnection

# deploy
# aws cloudformation deploy --template-file Infrastructure/codestar.yml --stack-name GhostGithubConnection