version: 0.2

# env:
#   git-credential-helper: yes
phases:
  # pre_build:
  #   commands:
  #     - git submodule update --init --recursive

  build:
    commands:
      - echo build docker image and push to ECR
      - ls
      - pwd
      - cd Ghost
      - docker build -t ghost . 
      - ACCOUNT_ID=`aws sts get-caller-identity --query "Account" --output text`
      - docker tag ghost $ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/ghost-blog:latest
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com
      - docker push $ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/ghost-blog:latest
      - echo Deploying to ECS
      - aws ecs update-service --cluster <cluster name> --service <service name> --force-new-deployment



artifacts:
  files:
    - 'Infrastructure/ghost_infra.yml'