# stackusing all the ghost templates

AWSTemplateFormatVersion: '2010-09-09'

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ['https://s3.amazonaws.com/${TemplatesBucket}/vpc.yml', TemplatesBucket: !ImportValue TemplatesBucket]

  ECS:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPC
    Properties:
      TemplateURL: !Sub ['https://s3.amazonaws.com/${TemplatesBucket}/ecs.yml', TemplatesBucket: !ImportValue TemplatesBucket]

  CloudFront:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPC
      - ECS
    Properties:
      TemplateURL: !Sub ['https://s3.amazonaws.com/${TemplatesBucket}/cloudfront.yml', TemplatesBucket: !ImportValue TemplatesBucket]

  TaskDefinition:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - RDS
      - ECS
      - VPC
      - CloudFront
    Properties:
      TemplateURL: !Sub ['https://s3.amazonaws.com/${TemplatesBucket}/tasks.yml', TemplatesBucket: !ImportValue TemplatesBucket]

  RDS:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPC
    Properties:
      TemplateURL: !Sub ['https://s3.amazonaws.com/${TemplatesBucket}/rds.yml', TemplatesBucket: !ImportValue TemplatesBucket]
  
  Lambda:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - CloudFront
    Properties:
      TemplateURL: !Sub ['https://s3.amazonaws.com/${TemplatesBucket}/lambda.yml', TemplatesBucket: !ImportValue TemplatesBucket]

  CloudTrail:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ['https://s3.amazonaws.com/${TemplatesBucket}/cloudtrail.yml', TemplatesBucket: !ImportValue TemplatesBucket]
    
  # Route53:
  #   Type: AWS::CloudFormation::Stack
  #   DependsOn:
  #     - ECS
  #     - CloudFront
  #   Properties:
  #     TemplateURL: !Sub ['https://s3.amazonaws.com/${TemplatesBucket}/route53.yml', TemplatesBucket: !ImportValue TemplatesBucket]

# deploy ghost stack
# aws cloudformation deploy --template-file Infrastructure/ghost_stack.yml --stack-name ghost-blog --capabilities CAPABILITY_IAM