AWSTemplateFormatVersion: '2010-09-09'
Description: Route53 routing for random-dev-domain.com to two given load balancers.

Resources:
  RandomDevDomainRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: random-dev-domain.com
      Type: A
      SetIdentifier: primary
      Failover: PRIMARY
      HostedZoneName: random-dev-domain.com.
      AliasTarget:
        DNSName: !ImportValue ELBDomainName
        HostedZoneId: !ImportValue ELBHostedZoneID
        EvaluateTargetHealth: true
      HealthCheckId:
        Ref: RandomDevDomainHealthCheck
  
  RandomDevDomainFailoverRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: random-dev-domain.com
      Type: A
      SetIdentifier: failover
      Failover: SECONDARY
      HostedZoneName: random-dev-domain.com.
      AliasTarget:
        DNSName: !ImportValue ELBDomainName
        HostedZoneId: !ImportValue ELBHostedZoneID
        EvaluateTargetHealth: true
      HealthCheckId:
        Ref: RandomDevDomainHealthCheck
  

  RandomDevDomainHealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: HTTP
        ResourcePath: /
        FullyQualifiedDomainName: !ImportValue ELBDomainName
        Port: 80
        RequestInterval: 10
        FailureThreshold: 3

# output the url
Outputs:
  RandomDevDomain:
    Value: !Join ['', ['http://', 'HostedZoneName: random-dev-domain.com']]
    Description: The url of the random-dev-domain.com


# deploy the stack
# aws cloudformation deploy --template-file Infrastructure/failover.yml --stack-name failover --capabilities CAPABILITY_IAM